### ISSUE TITLE
Lab 2 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab2-bobbyregan#1]
@bobbyregan 

1) Please use your name in the YAML

2) Please use proper Rmarkdown syntax for equation labels versus html tags which will only work in html...ie see for example line 51...which needs to be something like `(\#eq:label)`

3) On line 98 plese use inline r code versus hardcoding your numerical answers.

4) You should not hardcode the citations on line 102 for your packages...use instead `@R-packename`.

5) hide the output from the packages.bib creation code chunk.

The rest looks fine.

**Comment by bobbyregan** [comment]
@alanarnholt I have looked at these issues and I think I have resolved them

**Comment by alanarnholt** [comment]
@bobbyregan all corrections look good.  I noticed one other small detail: on line 78 you want to hyperlink the equation.  Instead of using `into 3.2` use something like into `\@ref(eq:f)`. I am closing issue.
